### ISSUE TITLE
The program should give a warning when the user attempts to assign non-related indices to an array.

### ISSUE THREAD

**Issue by NadiaSteyn** [TrystanScottLambert/Cross_Matching#4]
For example, consider:
idx_c,idx_cat,idx_not_matches_c,idx_not_matches_cat,d2d,d3d = cm.Cross_match(x_c,y_c,z_c,x_cat,y_cat,z_cat,xy_lim,z_lim)

Let's say 'c' has 20 elements, 'cat' has 10 elements, and the result is len(idx_c) = 15 and len(idx_cat) = 10. 

Since len(idx_c) > len(cat), the program will naturally crash if the user tries to use x_cat[idx_c].

Even though len(idx_cat) <= len(c), it is illogical to use x_c[idx_cat] 

Also illogical would be: x_c[idx_not_matches_cat] or x_cat[idx_not_matches_c].

**Comment by TrystanScottLambert** [comment]
Hi, I'm pretty sure that you shouldn't use x_cat[idx_c] in these cases. That even if the program didn't crash this would give you a logical error (nonsensical output). Ideally one would use the x_c[idx_c] and x_cat[idx_cat] i.e. keep cats together and c's together. 

This confusion can be clarified in documentation if any is to be written in the future.

**Comment by TrystanScottLambert** [comment]
Closing since this is a documentation request and we shan't be doing documentation in the foreseeable future.
